In [1]:
import numpy as np
import pandas as pd
import csv
import os
print(os.listdir("."))

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.pipeline import Pipeline
np.random.seed(0)

import warnings
warnings.filterwarnings('ignore')

['.ipynb_checkpoints', 'BankTweets.csv', 'BankTweets_04242020.csv', 'cbikkanur_twitter_credentials.ipynb', 'cbikkanur_twitter_credentials.json', 'CosineSimilarity.ipynb', 'documentSimilarity_TfIdf.ipynb', 'getTwitterData.ipynb', 'getTwitterData_TweePy.ipynb', 'SearchTweets.csv', 'SearchTweets_04242020.csv', 'tweets_04232020.csv', 'tweets_04242020.csv']


In [2]:
all_files = ['./tweets_04232020.csv', './tweets_04242020.csv']

df_list = []
for filename in all_files:
    df_list.append(pd.read_csv(filename, sep=',',header=0, encoding='utf-8', index_col = 0))
    
df_tweets = pd.concat(df_list, ignore_index=True)
df_tweets.tail()
       

Tweet_Id              User_Id       User_Name  \
5995  1253808235439706114  1160776206280736768           Steel   
5996  1253808231559753729           2603663594      James Eman   
5997  1253808227302510593           2868464198      Kim Wagner   
5998  1253808218909761538             69258603       Noel Jose   
5999  1253808218519863296            412136044  Mafeyisi Molea   

     User_Screen_Name   Theme  \
5995    Steel48653653  coffee   
5996        je_eman77  coffee   
5997       KimBWagner  coffee   
5998         noeljose  coffee   
5999     Therealmolea  coffee   

                                                   Text  
5995  @Facetiouslyfun @IttyTater @PumpkinPatch200 @I...  
5996  RT @joncoopertweets: I literally spit out my c...  
5997  RT @joncoopertweets: I literally spit out my c...  
5998  RT @mikhailquijano: Literally the sound of my ...  
5999  RT @Writers_Write: 'What on earth could be mor...

In [3]:
df = pd.DataFrame()
df['text'] = df_tweets['Text']
df.tail()

text
5995  @Facetiouslyfun @IttyTater @PumpkinPatch200 @I...
5996  RT @joncoopertweets: I literally spit out my c...
5997  RT @joncoopertweets: I literally spit out my c...
5998  RT @mikhailquijano: Literally the sound of my ...
5999  RT @Writers_Write: 'What on earth could be mor...

In [4]:
total_indices_size = df.shape[0]
train_size = 0.8
train_indices_size = int(train_size * total_indices_size)
test_indices_size = total_indices_size - train_indices_size
print(total_indices_size, train_indices_size, test_indices_size)

total_indices_array = np.array([x for x in range(total_indices_size)])
np.random.shuffle(total_indices_array)
train_indices, test_indices = total_indices_array[:train_indices_size], total_indices_array[train_indices_size:]

6000 4800 1200


In [5]:
train_set, test_set = df.loc[train_indices], df.loc[test_indices]
print(train_set.shape, test_set.shape)
train_set[:5]

(4800, 1) (1200, 1)


text
4320  @jeffersongraham 💙 Stay healthy and safe. We'r...
2006  @joshram @AmericanAir @AskCiti Just found out ...
5689                  @lilrayma tokyo bullet is quaking
472   @dubey1312 I apologize for the late response d...
1370  The annual Christmas with the Currys Winter Wo...

## CountVectorizer & Tf-Idf:

In [6]:
count_vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(1,3), \
                                   strip_accents='unicode', \
                                   analyzer = 'word',lowercase = True)
tfidf = TfidfTransformer()
pipeline = Pipeline(steps=[('count_vectorizer', count_vectorizer), ('tfidf', tfidf)])

tf_idf_train_matrix = pipeline.fit_transform(train_set["text"])
tf_idf_test_matrix = pipeline.transform(test_set["text"])

In [7]:
print(tf_idf_train_matrix.toarray())
print("Vector Shape:", tf_idf_test_matrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Vector Shape: (1200, 72660)


In [8]:
# Sanity check
cosine_similarities = cosine_similarity(tf_idf_test_matrix[2], tf_idf_train_matrix).flatten()
top_Indices = cosine_similarities.argsort()[::-1][:1].item(0)
top_tweet_Indices = train_indices[top_Indices]

print("\nInput Text:\n", df_tweets.loc[test_indices[2], "Text"], "\n")
print("\nSimilar Text:\n", df_tweets.loc[top_tweet_Indices, "Text"], "\n")


Input Text:
 Why are we not getting a paper towel or something to prevent it from going into the wall? Why are we just recording? Also, why the fuck hasnt your dog Beeb let out to pee? https://t.co/cz575yU0RT 


Similar Text:
 RT @fkajack: fuck it... dog vibin’ to kylie minogue https://t.co/ClMDR6rR9d 



In [9]:
def find_similar(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set_df, df_tweets):
    similar_text_list = []
    similar_score_list = []
    similar_theme_list = []
    for vector in tf_idf_test_matrix:
        cosine_similarities = cosine_similarity(vector, tf_idf_train_matrix).flatten()
        similar_doc_index =  cosine_similarities.argsort()[::-1][:1].item(0)
        top_tweet_Index = train_indices[similar_doc_index]
        similar_text_list.append(df_tweets.loc[top_tweet_Index, "Text"])
        similar_score_list.append(cosine_similarities[similar_doc_index])
        similar_theme_list.append(df_tweets.loc[top_tweet_Index, "Theme"])    
    
    df = test_set_df 
    df["original_theme"] = df_tweets.loc[test_indices, "Theme"]
    df["similar_text"] = similar_text_list
    df["similar_score"] = similar_score_list     
    df["similar_theme"] = similar_theme_list
    return df

In [10]:
similar_test_df = find_similar(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set, df_tweets)
similar_test_df

text  original_theme  \
5378  RT @FantasyDoggo: @Bypbap (Reuploaded cus I ha...             dog   
5980  love that i currently dont have to pay for gas...          coffee   
5395  Why are we not getting a paper towel or someth...             dog   
239   @tamihonesty2 We know frustrating this experie...  Bank/Financial   
5353  RT @chico_dykey: that is alot of pee. i know t...             dog   
542   @hanzield Hi there, I wanted to check back in ...  Bank/Financial   
2725  RT @MikeDentale: Airlines sending me “we’re in...        airlines   
2454  Carson Wentz should take a massive shit on the...             car   
1459  @1029Mo Hello, I received your DM and will res...  Bank/Financial   
3867  @kylejenks1 What songs are on your road trip p...  Bank/Financial   
1903  For the 10th year in a row, #Citi was named th...  Bank/Financial   
4648  RT @BofA_News: We have received over 85,000 ap...  Bank/Financial   
362   @ashleymarieh Hi Ashley. Can you tell me which...  Bank/Financial   
4645  @TheRealSchrader We have expanded the process ...  Bank/Financial   
2086  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
2988  RT @miiichaael: Coffee, anyone? ☕️ https://t.c...          coffee   
4177  @blaque_becky44 We cannot confirm if you have ...  Bank/Financial   
1730  RT @ConnieVerducci: ⁦@NYSE⁩ for the last openi...  Bank/Financial   
4451  @hamelkate Hi Kate. You can now complete your ...  Bank/Financial   
3607  RT @TheFiscalFemme: I'm partnering up with @So...  Bank/Financial   
3984            @Garrettworden4 https://t.co/RBFpiHCX4J  Bank/Financial   
3347  @_alextai Hi there, yes, how long ago did you ...  Bank/Financial   
2083  Since 2016 @JPMorgan @Chase, @Citi, @BankofAme...           @Citi   
2845  RT @Hossamghazi2: Perhaps ramadan brings mirac...         ramadan   
4891  Congratulations to Jane Fraser, Ida Liu and Ma...  Bank/Financial   
4650  RT @clt_alliance: In this week's edition of CL...  Bank/Financial   
3004  It’s simple to set up a payment account in the...  Bank/Financial   
4789  RT @BofA_News: Our thoughts are with the victi...  Bank/Financial   
1181  @CooperDahalia hi, please contact us at the nu...  Bank/Financial   
3599  @RandyMays Hi Randy. Sorry for the delay in ou...  Bank/Financial   
...                                                 ...             ...   
797   If you need support we are open for business a...  Bank/Financial   
755   Please join the Reddit AMA here: https://t.co/...  Bank/Financial   
2008  RT @Citi: "People who are successful at #Citi ...           @Citi   
99    🚨 Citi / AAdvantage Cardmembers 🚨 Latin Pop Ic...  Bank/Financial   
2496  i use to listen to this song with a friend. in...             car   
1871  The pace of technological change in the Middle...  Bank/Financial   
2046  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
4851  Tyler Dickson, Global Co-Head of Banking, Capi...  Bank/Financial   
5072  RT @Citi: How do you innovate? Our CEO Mike Co...           @Citi   
2163  RT @PhilippineStar: JUST IN: The IATF has reco...        covid-19   
2893  RT @MesutOzil1088: Ramadan Mubarak to all my M...         ramadan   
537   @liuj12 We haven't heard back from you. Feel f...  Bank/Financial   
1701  RT @ChiMarathon: Why are you running the 2020 ...  Bank/Financial   
2897  RT @Hakakluah: May this blessed month bring us...         ramadan   
2222  The tragedy of turning the cake 5 minutes befo...            cake   
2135  RT @GOPChairwoman: State Rep. Whitsett nearly ...        covid-19   
2599  RT @ScottishSun: First geological map of the M...            nasa   
705   📢 #SoFiNews Update:\n💬 @WhatsApp makes moves t...  Bank/Financial   
3468  @liiisajx Please let us know any errors you ar...  Bank/Financial   
5924  The healthiest way to brew your coffee -- and ...          coffee   
5874  #culturallyresponsiveeducation Happy Ramadan t...         ramadan   
4373  RT @CameronNewton: Time has come for our 6th A...  Bank/Financial   
1

In [11]:
accuracy = 100 * np.sum(similar_test_df["original_theme"] == similar_test_df["similar_theme"])/similar_test_df.shape[0]
print("Accuracy on test data in predicting theme: {}%".format(np.round(accuracy,2)))

Accuracy on test data in predicting theme: 90.5%
