In [6]:
import numpy as np
import pandas as pd
import csv
import os
print(os.listdir("."))

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.pipeline import Pipeline


import warnings
warnings.filterwarnings('ignore')

['.ipynb_checkpoints', 'BankTweets.csv', 'cbikkanur_twitter_credentials.ipynb', 'cbikkanur_twitter_credentials.json', 'CosineSimilarity.ipynb', 'documentSimilarity_TfIdf-Copy1.ipynb', 'documentSimilarity_TfIdf.ipynb', 'getTwitterData.ipynb', 'getTwitterData_TweePy.ipynb', 'SearchTweets.csv', 'tweets_04232020.csv']


In [2]:
df_tweets = pd.read_csv('./tweets_04232020.csv', sep=',',header=0, encoding='utf-8', index_col = 0)
df_tweets.head()

Tweet_Id   User_Id User_Name User_Screen_Name           Theme  \
0  1253375593271394312  80374332  Citibank         Citibank  Bank/Financial   
1  1253322747851296768  80374332  Citibank         Citibank  Bank/Financial   
2  1253066045700681731  80374332  Citibank         Citibank  Bank/Financial   
3  1252960358454767616  80374332  Citibank         Citibank  Bank/Financial   
4  1252673469852143618  80374332  Citibank         Citibank  Bank/Financial   

                                                Text  
0  Registering for online access and activating y...  
1  Protect your CARES Act payments: Validate comm...  
2  It’s simple to set up a payment account in the...  
3  We’re committed to helping provide the support...  
4  Protect Yourself from COVID-19 Scams: Don’t re...

In [3]:
df = pd.DataFrame()
df['text'] = df_tweets['Text']
df.tail()

text
2995  RT @fairycakes: No one: \n\nArticle about an a...
2996  RT @Mom_Overboard: Mom culture is putting a co...
2997  RT @soxloverhk: Coffee break https://t.co/kamo...
2998        Next is decaf you brew it just like coffee.
2999                    coffee tastes so good at night🖤

In [4]:
total_indices = df_tweets.shape[0]
total_indices_array = np.array([x for x in range(total_indices)])
np.random.seed(0)
np.random.shuffle(total_indices_array)
print(total_indices_array[:5])


train_indices, test_indices = total_indices_array[:2700], total_indices_array[2700:]
print(train_indices[:5])

[ 311 1025 1587 2941 2980]
[ 311 1025 1587 2941 2980]


In [5]:
train_set, test_set = df.loc[train_indices], df.loc[test_indices]
print(train_set.shape, test_set.shape)
train_set[:5]

(2700, 1) (300, 1)


text
311   @dane206 Good Morning. Please call us directly...
1025  @Carmen67336604 We apologize for the higher th...
1587  @siehavas We apologize for how you're feeling,...
2941  @leeoralexandra I did 60 hrs a couple years ag...
2980  Whipped coffee is the best thing I never knew ...

## CountVectorizer & Tf-Idf:

In [20]:
count_vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(1,3), \
                                   strip_accents='unicode', \
                                   analyzer = 'word',lowercase = True)
tfidf = TfidfTransformer()
pipeline = Pipeline(steps=[('count_vectorizer', count_vectorizer), ('tfidf', tfidf)])

tf_idf_train_matrix = pipeline.fit_transform(train_set["text"])
tf_idf_test_matrix = pipeline.transform(test_set["text"])

In [21]:
print(tf_idf_train_matrix.toarray())
print("Vector Shape:", tf_idf_test_matrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Vector Shape: (300, 55352)


In [23]:
# Sanity check
cosine_similarities = cosine_similarity(tf_idf_test_matrix[2], tf_idf_train_matrix).flatten()
top_Indices = cosine_similarities.argsort()[::-1][:1].item(0)
top_tweet_Indices = train_indices[top_Indices]

print("\nInput Text:\n", df_tweets.loc[test_indices[2], "Text"], "\n")
print("\nSimilar Text:\n", df_tweets.loc[top_tweet_Indices, "Text"], "\n")


Input Text:
 @carinad95 @HiltonHotels you're welcome, thank you for your service. 


Similar Text:
 @j_rice5 you're welcome, thank you for sharing your feedback! ^A 



In [24]:
def find_similar(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set_df, df_tweets):
    similar_text_list = []
    similar_score_list = []
    similar_theme_list = []
    for vector in tf_idf_test_matrix:
        cosine_similarities = cosine_similarity(vector, tf_idf_train_matrix).flatten()
        similar_doc_index =  cosine_similarities.argsort()[::-1][:1].item(0)
        top_tweet_Index = train_indices[similar_doc_index]
        similar_text_list.append(df_tweets.loc[top_tweet_Index, "Text"])
        similar_score_list.append(cosine_similarities[similar_doc_index])
        similar_theme_list.append(df_tweets.loc[top_tweet_Index, "Theme"])    
    
    df = test_set_df 
    df["original_theme"] = df_tweets.loc[test_indices, "Theme"]
    df["similar_text"] = similar_text_list
    df["similar_score"] = similar_score_list     
    df["similar_theme"] = similar_theme_list
    return df

In [25]:
similar_test_df = find_similar(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set, df_tweets)
similar_test_df

text  original_theme  \
809   The health &amp; well-being of our customers, ...  Bank/Financial   
433   @thingblue Thanks for reaching out, if any oth...  Bank/Financial   
1107  @carinad95 @HiltonHotels you're welcome, thank...  Bank/Financial   
2091  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
860   @tspeakn0w As spots open up on the wait list w...  Bank/Financial   
274   @Nicole_813 1. Log in to your Bluebird Account...  Bank/Financial   
967   @lljillibean This just left is breathless! #Ja...  Bank/Financial   
2962  RT @fairycakes: No one: \n\nArticle about an a...          coffee   
2139  RT @RollingStone: Amy Poehler, Chris Pratt, Ni...        covid-19   
1346  Congratulations to our very own @sekou_kaalund...  Bank/Financial   
885   @chadmercer_ Pinch yourself because it is real...  Bank/Financial   
556   @hestiahdruid Hello. Thanks for contacting us....  Bank/Financial   
908   @mollyswindall Don't worry, successfully regis...  Bank/Financial   
1381  Transitioning from military to civilian life i...  Bank/Financial   
2117  RT @cbcnewsbc: Beyond the numbers in the COVID...        covid-19   
2562       @imhcloudss those are great things to love 🤍            nasa   
509   @MisterSEvans We'd be glad to review your situ...  Bank/Financial   
2388  @dog_rates Brilliant tweet.  13/10 would read ...             dog   
221   @Jav0126  Thanks. Honestly, I'm not sure as I ...  Bank/Financial   
1297  @GetwellwithElle @mikerotman @PNCBank Please v...  Bank/Financial   
146   It's time to heat up your summer with one of t...  Bank/Financial   
1777  We’re proud to extend our partnership with @RE...  Bank/Financial   
1053  @MoJoviSPN looping in @AskAmex to help look in...  Bank/Financial   
1822  “In our Institutional Clients Group, we had st...  Bank/Financial   
508   @RandyMays Hi Randy. Sorry for the delay in ou...  Bank/Financial   
323   @PRDR123 If you have time to chat securely wit...  Bank/Financial   
1561  @signmysigns Hi. As stated in the email, you a...  Bank/Financial   
176   Four well-traveled experts give tips for mixin...  Bank/Financial   
1908  As #BlackHistoryMonth comes to a close, we loo...  Bank/Financial   
168   .@LennonStella’s Three. Two. One: The Tour is ...  Bank/Financial   
...                                                 ...             ...   
2496  i use to listen to this song with a friend. in...             car   
1871  The pace of technological change in the Middle...  Bank/Financial   
2046  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
755   Please join the Reddit AMA here: https://t.co/...  Bank/Financial   
976   @emily_giglio It's gonna be a peachin' good ti...  Bank/Financial   
2163  RT @PhilippineStar: JUST IN: The IATF has reco...        covid-19   
1940  #Citi proudly supports @nyulangone's Playing f...  Bank/Financial   
2825  RT @SpongeBob: wishing everyone a Happy Ramada...         ramadan   
2120  RT @myogiadityanath: Over 93% Indians trust Ho...        covid-19   
2893  RT @MesutOzil1088: Ramadan Mubarak to all my M...         ramadan   
537   @liuj12 We haven't heard back from you. Feel f...  Bank/Financial   
1701  RT @ChiMarathon: Why are you running the 2020 ...  Bank/Financial   
2897  RT @Hakakluah: May this blessed month bring us...         ramadan   
2222  The tragedy of turning the cake 5 minutes befo...            cake   
2135  RT @GOPChairwoman: State Rep. Whitsett nearly ...        covid-19   
2599  RT @ScottishSun: First geological map of the M...            nasa   
705   📢 #SoFiNews Update:\n💬 @WhatsApp makes moves t...  Bank/Financial   
2362  @judgingurn @suzy_swears If you think sticking...             dog   
2648  This book is written in easy-to-understand lan...           tokyo   
2647  If you would open a restaurant in Tokyo, what ...           tokyo   
1828  Download the Citi® News App to review Citi’s f...  Bank/Financial   
1778  RT @IAmAlyseZwick: Hey NYC...\n🎶It’s beginning...  Bank/Financial   
2

In [26]:
accuracy = 100 * np.sum(similar_test_df["original_theme"] == similar_test_df["similar_theme"])/similar_test_df.shape[0]
print("Accuracy on test data in predicting theme: {}%".format(np.round(accuracy,2)))

Accuracy on test data in predicting theme: 88.67%
