In [1]:
import numpy as np
import pandas as pd
import csv
import os
print(os.listdir("."))

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.pipeline import Pipeline
np.random.seed(0)

import warnings
warnings.filterwarnings('ignore')

['.ipynb_checkpoints', 'BankTweets.csv', 'BankTweets_04242020.csv', 'BankTweets_04252020.csv', 'BankTweets_04262020.csv', 'BankTweets_04292020.csv', 'cbikkanur_twitter_credentials.ipynb', 'cbikkanur_twitter_credentials.json', 'CosineSimilarity.ipynb', 'documentSimilarity.ipynb', 'documentSimilarity_TfIdf.ipynb', 'documentSimilarity_TfIdf.ipynb.txt', 'getTwitterData.ipynb', 'getTwitterData_TweePy.ipynb', 'model_save', 'SearchTweets.csv', 'SearchTweets_04242020.csv', 'SearchTweets_04252020.csv', 'SearchTweets_04262020.csv', 'SearchTweets_04292020.csv', 'test_vectors.npy', 'TfIdf_similar_test_tweets.csv', 'train_vectors.npy', 'tweets_04232020.csv', 'tweets_04242020.csv', 'tweets_04252020.csv', 'tweets_04262020.csv', 'tweets_04292020.csv']


In [2]:
all_files = ['./tweets_04232020.csv', './tweets_04242020.csv', './tweets_04252020.csv', './tweets_04262020.csv', './tweets_04292020.csv']

df_list = []
for filename in all_files:
    df_list.append(pd.read_csv(filename, sep=',',header=0, encoding='utf-8', index_col = 0))
    
df_tweets = pd.concat(df_list, ignore_index=True)
df_tweets       

Tweet_Id              User_Id  \
0      1253375593271394312             80374332   
1      1253322747851296768             80374332   
2      1253066045700681731             80374332   
3      1252960358454767616             80374332   
4      1252673469852143618             80374332   
5      1252605509867384837             80374332   
6      1252356369153290240             80374332   
7      1252311072079519744             80374332   
8      1251986429816852480             80374332   
9      1251668546540703744             80374332   
10     1251661847255822338             80374332   
11     1251616387254095875             80374332   
12     1251613504584462336             80374332   
13     1251513855957766144             80374332   
14     1251245296400637954             80374332   
15     1251148445928153089             80374332   
16     1250891727868702727             80374332   
17     1250521211064520707             80374332   
18     1250098924146302976             80374332   
19     1250061248407965700             80374332   
20     1249781913172217869             80374332   
21     1249751706847633410             80374332   
22     1249722812257927173             80374332   
23     1249094881592500224             80374332   
24     1249011830544048130             80374332   
25     1248693481536659458             80374332   
26     1248279507267727362             80374332   
27     1248260858465091584             80374332   
28     1248260845790003200             80374332   
29     1247903973240999941             80374332   
...                    ...                  ...   
14970  1255520246502473728            195950334   
14971  1255520245235793921            426903572   
14972  1255520243801350144           1195504494   
14973  1255520241817436161             75901533   
14974  1255520241255251968  1048427992131596288   
14975  1255520240949174272   996471531038441472   
14976  1255520238835322881  1252772234646695936   
14977  1255520236134182928   727656874330357760   
14978  1255520235219795968           1418234742   
14979  1255520233848287238   790033898960920576   
14980  1255520233470787585   997192114088820736   
14981  1255520231327510528           2416741900   
14982  1255520230408847360  1069009023213559811   
14983  1255520227149914115           2835760449   
14984  1255520222485770241  1097176269265850369   
14985  1255520222443954176           3308338931   
14986  1255520222179741697  1047128589387423744   
14987  1255520222146187266            242271778   
14988  1255520221273755649  1055109281018667008   
14989  1255520220250284036           2216440937   
14990  1255520219298234369            176166648   
14991  1255520215603056640   835130367883489282   
14992  1255520214835294213           3376584558   
14993  1255520214797647872           1297434740   
14994  1255520214462222339             25183700   
14995  1255520212260175872  1051372512582328321   
14996  1255520211610075136             16383553   
14997  1255520210041348096            547284373   
14998  1255520209500323842            355634795   
14999  1255520206711074817           2159921089   

                             User_Name User_Screen_Name           Theme  \
0                             Citibank         Citibank  Bank/Financial   
1                             Citibank         Citibank  Bank/Financial   
2                             Citibank         Citibank  Bank/Financial   
3                             Citibank         Citibank  Bank/Financial   
4                             Citibank         Citibank  Bank/Financial   
5                             Citibank         Citibank  Bank/Financial   
6                             Citibank         Citibank  Bank/Financial   
7                             Citibank         Citibank  Bank/Financial   
8                             Citibank         Citibank  Bank/Financial   
9                             Citibank         Citibank  Bank/Financial   
10                            

In [3]:
df_tweets.drop_duplicates(["Text", "User_Id"], inplace=True) # remove duplicates in place and reset index
df_tweets = df_tweets.reset_index(drop=True)
df_tweets.shape

(7958, 6)

In [4]:
df = pd.DataFrame()
df['text'] = df_tweets['Text']
df.tail()

text
7953  RT @lucxs__x: You're the coffee that I need in...
7954  RT @RoberteLove: I had to go to the store this...
7955  @mykalmphoto Nice photos.  When this is all ov...
7956  RT @minturnalexandr: Ten years ago I bought th...
7957  RT @IvankaTrump: Small businesses like Amy Wri...

In [5]:
total_indices_size = df.shape[0]
train_size = 0.8
train_indices_size = int(train_size * total_indices_size)
test_indices_size = total_indices_size - train_indices_size
print('Total records: {} \nTrain records: {} \n Test records: {}'.format(total_indices_size, train_indices_size, test_indices_size))

total_indices_array = np.array([x for x in range(total_indices_size)])
np.random.shuffle(total_indices_array)
train_indices, test_indices = total_indices_array[:train_indices_size], total_indices_array[train_indices_size:]

Total records: 7958 
Train records: 6366 
 Test records: 1592


In [6]:
train_set, test_set = df.loc[train_indices], df.loc[test_indices]
print(train_set.shape, test_set.shape)
train_set[:5]

(6366, 1) (1592, 1)


text
2459  @ImHerMajesty Get a truck. I want my next car ...
7208  (That's a cake using LEGO bricks. Not an actua...
3067  @J_C_Shin Hi thanks for reaching out. It's imp...
5900  RT @LetsWeeb: Why does this dog look like it j...
274   @theliftsavage Hi. No, this is not something w...

## CountVectorizer & Tf-Idf:

In [7]:
count_vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(1,3), \
                                   strip_accents='unicode', \
                                   analyzer = 'word',lowercase = True)
tfidf = TfidfTransformer()
pipeline = Pipeline(steps=[('count_vectorizer', count_vectorizer), ('tfidf', tfidf)])

tf_idf_train_matrix = pipeline.fit_transform(train_set["text"])
tf_idf_test_matrix = pipeline.transform(test_set["text"])

In [8]:
print(tf_idf_train_matrix.toarray())
print("Vector Shape:", tf_idf_test_matrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Vector Shape: (1592, 120508)


In [9]:
def print_similar_texts(query_text, query_text_vector,  train_matrix, train_indices, df_tweets, n = 5):
    cosine_similarities_n = cosine_similarity(query_text_vector, train_matrix).flatten()
    top_Indices = cosine_similarities_n.argsort()[::-1][:n]
    top_tweet_Indices = train_indices[top_Indices]
    
    print('\nInput Text:\n {} \n'.format(query_text))
    for index, sim_text in enumerate(df_tweets.loc[top_tweet_Indices, "Text"]):
        print('*' * 35, 'Similar Text: {} || Similar Score: {}'.format(index+1, np.round(cosine_similarities_n[top_Indices[index]], 3)), '*' * 35, '\n')
        print(sim_text, '\n')

In [10]:
query_index = 5
query_text = df_tweets.loc[test_indices[query_index], "Text"]
query_text_vector = tf_idf_test_matrix[query_index]
print_similar_texts(query_text, query_text_vector, tf_idf_train_matrix, train_indices, df_tweets, n = 5)


Input Text:
 @xoxjessiica I am sorry to hear this. It should appear on the next or following statement. To forward to our internal team on your behalf, DM account/card type only, full name and contact phone number already on profile. No PIN or account numbers. ^Deanna https://t.co/gvC4jAOA9c 

*********************************** Similar Text: 1 || Similar Score: 0.387 *********************************** 

@conorFa16113956 We suggest deleting the previous public tweet and DM the full name, and contact phone number only that is already on profile. Email and Twitter are not secure banking communication channels. Do not DM any PIN or account numbers. ^Deanna https://t.co/gvC4jAOA9c 

*********************************** Similar Text: 2 || Similar Score: 0.345 *********************************** 

@this_is_Manu Thanks for reaching out. We are here to help. Let us review this further. DM the account/card type only (checking, credit card, retail branded store card, etc) and country where it w

In [11]:
def find_similar_n(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set_df, df_tweets, n=5):
    similar_texts_list = []
    similar_scores_list = []
    similar_top_score_list = []
    similar_themes_list = []
    similar_top_themes_list = []
    for vector in tf_idf_test_matrix:
        cosine_similarities_n = cosine_similarity(vector, tf_idf_train_matrix).flatten()
        similar_doc_indices =  cosine_similarities_n.argsort()[::-1][:n]
        top_tweet_Indices = train_indices[similar_doc_indices]
        
        similar_texts = [text for text in df_tweets.loc[top_tweet_Indices, "Text"]]
        similar_texts_list.append(similar_texts)
        
        similar_scores = [np.round(score, 3) for score in cosine_similarities_n[similar_doc_indices]]
        similar_scores_list.append(similar_scores)
        similar_top_score_list.append(similar_scores[0])
                                                                   
        similar_themes = [theme for theme in df_tweets.loc[top_tweet_Indices, "Theme"]]
        similar_themes_list.append(similar_themes)
        
        top_similar_theme = max(set(similar_themes), key=lambda x: similar_themes.count(x))
        similar_top_themes_list.append(top_similar_theme)
    
    df = test_set_df 
    df["original_theme"] = df_tweets.loc[test_indices, "Theme"]
    df["similar_texts"] = similar_texts_list
    df["similar_scores"] = similar_scores_list  
    df["top_similar_score"] = similar_top_score_list
    df["similar_themes"] = similar_themes_list
    df["top_similar_themes"] = similar_top_themes_list
    return df

In [12]:
similar_test_df = find_similar_n(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set, df_tweets, n=10)
similar_test_df

text  original_theme  \
6953  RT @Essence: Join us TOMORROW, 4/27 at 7 PM ES...  Bank/Financial   
6031  RT @Jordan_Sather_: I can (almost) guarantee y...            nasa   
239   @roth_jroth1515 Hi Jennifer. Do you have a mom...  Bank/Financial   
5720  RT @gguksluver: jimins face when he realized j...            cake   
7102  RT @SaralPatel: Shri @RahulGandhi will be inte...        covid-19   
542   @xoxjessiica I am sorry to hear this. It shoul...  Bank/Financial   
2725  RT @MikeDentale: Airlines sending me “we’re in...        airlines   
2454  @Yo_ItsMONROE EVERY! One. The one where i live...             car   
1459  @PSCC_Tualatin Hi Jonathan, the applications a...  Bank/Financial   
5764  RT @ZorbitsMath: Extra! Extra! For today’s #Zo...            cake   
3867  RT @AsemWORLD: Freestyle Friday S2Ep11 \nClima...           tokyo   
1903  #Citi appoints Kristine Braden as Head of the ...  Bank/Financial   
4648  'no cake only lasagna'\n\nI had to make this c...            cake   
362   @Candicontreras7 Hello, thank you for tweeting...  Bank/Financial   
4645  RT @_HaileyQueen_: eat all that cake 😋🍑 https:...            cake   
2086  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
2988                    coffee tastes so good at night🖤          coffee   
4177  @Tea4Lynne Hi there, thank you for reaching ou...  Bank/Financial   
1730  Learn how Duane Topping's battle with PTSD too...  Bank/Financial   
5816     Or a dog :&lt;&lt;&lt; https://t.co/jbCOoFIrWH             dog   
4451  RT @Citi: Jane Fraser discusses how business l...           @Citi   
3607  i mean he really was drunk in the back of the ...             car   
3984                 @horusblog Lolllz\n\nHappy Ramadan         ramadan   
3347  @IgnoreNarrative @MasaSonCap They are amazing....        covid-19   
2083  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
2845  RT @MesutOzil1088: Ramadan Mubarak to all my M...         ramadan   
6476                     Coffee https://t.co/Cp4Qq0K9Ad          coffee   
4650  Alas, poor Yorick”\n\nSkull Cake... chocolate ...            cake   
3004  @BronxAdjacent Hi. I never heard back from you...  Bank/Financial   
4789  Do you have a cat or dog?\n\nYes. https://t.co...             dog   
...                                                 ...             ...   
6216  RT @The_Real_Fly: U.S. airlines receive extra ...        airlines   
2893  yo its a wrap for costco and trader joe sample...          coffee   
537   @hanzield Hi there, I wanted to check back in ...  Bank/Financial   
1701  RT @shareclt: Introducing: Wish List Wednesday...  Bank/Financial   
2897  RT @novelolizz: I need coffee before I start m...          coffee   
7768  RT @Diegochuene: Hit a like if you agree \n st...         ramadan   
2222  RT @cyrilswhore: I'm sorry but there's nothing...            cake   
2135  Covid-19 may have the state shut down, but I’m...        covid-19   
2599  RT @AestheticsJapan: Tokyo Prefecture\nby http...           tokyo   
7654  RT @Owakita_: Loved going to this spot to take...           tokyo   
705                             https://t.co/BD7lU05Akg  Bank/Financial   
6458  RT @ElliottBlackwe3: Name a fictional characte...          coffee   
3468  @Bronze_Sunshine @TAMPONSTRlNG @bluemiiints @F...            cake   
6744  @MeimeiGlamz Hi, were you able to get your iss...  Bank/Financial   
7640  RT @pamgyu: TXT's trailer song and tokyo have ...           tokyo   
7238  Silversons' Cake "Roulette" Recipe! https://t....            cake   
6743  @RubenLDante Hi Ruben, I regret any frustratio...  Bank/Financial   
5924  RT @rxsaini1: parked car conversations hit dif...             car   
5874                    Try dog https://t.co/ULMFWAAP2T             dog   
4373  @Buttany_Brian Thank you for providing that in...  Bank/Financial   
7891  RT @V_actually: 2/3\nThis coffee shop is one o...          coffee   
1033  @Calysurfer Unfortunately, we are experiencing...  Bank/Financial   
7

In [13]:
accuracy = 100 * np.sum(similar_test_df["original_theme"] == similar_test_df["top_similar_themes"])/similar_test_df.shape[0]
print("Accuracy on test data in predicting theme: {}%".format(np.round(accuracy,2)))

Accuracy on test data in predicting theme: 81.97%


In [14]:
similar_test_df.to_csv("TfIdf_similar_test_tweets.csv")