In [12]:
import numpy as np
import pandas as pd
import csv
import os
print(os.listdir("."))

from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.pipeline import Pipeline
np.random.seed(0)

import warnings
warnings.filterwarnings('ignore')

['.ipynb_checkpoints', 'BankTweets.csv', 'cbikkanur_twitter_credentials.ipynb', 'cbikkanur_twitter_credentials.json', 'CosineSimilarity.ipynb', 'documentSimilarity_TfIdf.ipynb', 'getTwitterData.ipynb', 'getTwitterData_TweePy.ipynb', 'SearchTweets.csv', 'tweets_04232020.csv']


In [5]:
df_tweets = pd.read_csv('./tweets_04232020.csv', sep=',',header=0, encoding='utf-8', index_col = 0)
df_tweets.head()

Tweet_Id   User_Id User_Name User_Screen_Name           Theme  \
0  1253375593271394312  80374332  Citibank         Citibank  Bank/Financial   
1  1253322747851296768  80374332  Citibank         Citibank  Bank/Financial   
2  1253066045700681731  80374332  Citibank         Citibank  Bank/Financial   
3  1252960358454767616  80374332  Citibank         Citibank  Bank/Financial   
4  1252673469852143618  80374332  Citibank         Citibank  Bank/Financial   

                                                Text  
0  Registering for online access and activating y...  
1  Protect your CARES Act payments: Validate comm...  
2  It’s simple to set up a payment account in the...  
3  We’re committed to helping provide the support...  
4  Protect Yourself from COVID-19 Scams: Don’t re...

In [6]:
df = pd.DataFrame()
df['text'] = df_tweets['Text']
df.tail()

text
2995  RT @fairycakes: No one: \n\nArticle about an a...
2996  RT @Mom_Overboard: Mom culture is putting a co...
2997  RT @soxloverhk: Coffee break https://t.co/kamo...
2998        Next is decaf you brew it just like coffee.
2999                    coffee tastes so good at night🖤

In [25]:
total_indices_size = df.shape[0]
train_size = 0.8
train_indices_size = int(train_size * total_indices_size)
test_indices_size = total_indices_size - train_indices_size
print(total_indices_size, train_indices_size, test_indices_size)

total_indices_array = np.array([x for x in range(total_indices_size)])
np.random.shuffle(total_indices_array)
train_indices, test_indices = total_indices_array[:train_indices_size], total_indices_array[train_indices_size:]

3000 2400 600


In [26]:
train_set, test_set = df.loc[train_indices], df.loc[test_indices]
print(train_set.shape, test_set.shape)
train_set[:5]

(2400, 1) (600, 1)


text
2193  RT @ksadjadpour: A day in the life of Donald T...
745   Here’s how to contact us.\nStudent loans: http...
1128  @stilldevelopin5 hi, connecting you to our cus...
1337  For Noelle Santos, founder of @thelitbar, open...
2669  RT @inoueart: Inoue Takehiko drew a painting o...

## CountVectorizer & Tf-Idf:

In [27]:
count_vectorizer = CountVectorizer(stop_words = 'english', ngram_range=(1,3), \
                                   strip_accents='unicode', \
                                   analyzer = 'word',lowercase = True)
tfidf = TfidfTransformer()
pipeline = Pipeline(steps=[('count_vectorizer', count_vectorizer), ('tfidf', tfidf)])

tf_idf_train_matrix = pipeline.fit_transform(train_set["text"])
tf_idf_test_matrix = pipeline.transform(test_set["text"])

In [28]:
print(tf_idf_train_matrix.toarray())
print("Vector Shape:", tf_idf_test_matrix.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Vector Shape: (600, 50612)


In [29]:
# Sanity check
cosine_similarities = cosine_similarity(tf_idf_test_matrix[2], tf_idf_train_matrix).flatten()
top_Indices = cosine_similarities.argsort()[::-1][:1].item(0)
top_tweet_Indices = train_indices[top_Indices]

print("\nInput Text:\n", df_tweets.loc[test_indices[2], "Text"], "\n")
print("\nSimilar Text:\n", df_tweets.loc[top_tweet_Indices, "Text"], "\n")


Input Text:
 Commercial cards have a crucial role to play in the digitization of the B2B payment experience. Learn more: https://t.co/L1HVpy19P5 https://t.co/yySulJIXkT 


Similar Text:
 #Citi Commercial Cards has launched an intelligent virtual agent capability within its call centers in the U.S., leveraging technology from @interactionsco, a leading conversational AI company. Learn more: https://t.co/CvRMEeN342 



In [30]:
def find_similar(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set_df, df_tweets):
    similar_text_list = []
    similar_score_list = []
    similar_theme_list = []
    for vector in tf_idf_test_matrix:
        cosine_similarities = cosine_similarity(vector, tf_idf_train_matrix).flatten()
        similar_doc_index =  cosine_similarities.argsort()[::-1][:1].item(0)
        top_tweet_Index = train_indices[similar_doc_index]
        similar_text_list.append(df_tweets.loc[top_tweet_Index, "Text"])
        similar_score_list.append(cosine_similarities[similar_doc_index])
        similar_theme_list.append(df_tweets.loc[top_tweet_Index, "Theme"])    
    
    df = test_set_df 
    df["original_theme"] = df_tweets.loc[test_indices, "Theme"]
    df["similar_text"] = similar_text_list
    df["similar_score"] = similar_score_list     
    df["similar_theme"] = similar_theme_list
    return df

In [31]:
similar_test_df = find_similar(tf_idf_train_matrix, train_indices, tf_idf_test_matrix, test_indices, test_set, df_tweets)
similar_test_df

text  original_theme  \
2590  RT @notsoevilrick: NASA faked the cow jumping ...            nasa   
1208  @jwgvico @ChaseforBiz We'll be sending a follo...  Bank/Financial   
1912  Commercial cards have a crucial role to play i...  Bank/Financial   
2311           @MySportsUpdate raiders fans got a DOG!!             dog   
1266  @butch17372553 We’re updating the site to make...  Bank/Financial   
1044  @LynneSmithGA Connecting you with @AskAmex to ...  Bank/Financial   
1159  @duris Please give us a call using the number ...  Bank/Financial   
386              @CampPantsz No, I'm sorry we don't. ^B  Bank/Financial   
2091  RT @SierraClub: BIG NEWS: Responding to pressu...           @Citi   
23    Healthcare workers on the frontline fighting t...  Bank/Financial   
754   @getnfiredup Hey, we'd like to help you in any...  Bank/Financial   
2184  https://t.co/HhZ8Ex2IWP - A Teenager Posted Ab...        covid-19   
1847  RT @WSJ: Citi’s head of mergers and acquisitio...  Bank/Financial   
1828  Download the Citi® News App to review Citi’s f...  Bank/Financial   
2644  Olympic organizers say delaying the Tokyo 2020...           tokyo   
2     It’s simple to set up a payment account in the...  Bank/Financial   
2142  RT @JCAPoquoson: Punished for telling the trut...        covid-19   
105   #CitiPresale tix are available NOW for Stone P...  Bank/Financial   
743   Since we’re all spending so much time on video...  Bank/Financial   
36    Are you looking for Citi support? Send us a pr...  Bank/Financial   
2780  RT @MikeDentale: Airlines sending me “we’re in...        airlines   
1535  @curbedcomedy Hi. We are providing assistance ...  Bank/Financial   
765   We’re getting a head start on Equal Pay Day an...  Bank/Financial   
2280  Fruits Cake For Wishing You Happy And Healthy ...            cake   
954   @Juanita_Steph We got you! We'll see you at #J...  Bank/Financial   
1139  @judypu1 yes, please forward to spoof@american...  Bank/Financial   
216   @_sonite Please call the number on the back of...  Bank/Financial   
1783  RT @MastercardNews: .@Mastercard &amp; @Bankof...  Bank/Financial   
1563  @ocsmitty960 Thank you, Olivia! We truly are w...  Bank/Financial   
1773  Take a stroll through the outdoor holiday shop...  Bank/Financial   
...                                                 ...             ...   
125   Attention golf fans - If you’re a cardmember a...  Bank/Financial   
1914  At Citi, we’re being honest with ourselves abo...  Bank/Financial   
1377  Congratulations to our very own @Thasunda Duck...  Bank/Financial   
483   @Omnious Glad to hear that you were able to ge...  Bank/Financial   
117   .@ItsTonyBennett is heading to the beautiful @...  Bank/Financial   
1039  @Calysurfer Unfortunately, we are experiencing...  Bank/Financial   
2805  RT @SpongeBob: wishing everyone a Happy Ramada...         ramadan   
1265  @soniayoumans You can complete your applicatio...  Bank/Financial   
1381  Transitioning from military to civilian life i...  Bank/Financial   
171   What's the buzziest new hotel amenity? Think: ...  Bank/Financial   
1850  Citi appoints former Danish PM and head of NAT...  Bank/Financial   
327   @TrishMortarott1 @angelic66815849 @IRStaxpros ...  Bank/Financial   
3     We’re committed to helping provide the support...  Bank/Financial   
161   Discover Chicago’s distinct neighborhoods that...  Bank/Financial   
396   @JefeJmorsberger Hi there Jeff, thanks for rea...  Bank/Financial   
267   @LaurenFulcher Hi Lauren, perhaps I can help y...  Bank/Financial   
2967  RT @mathmania64: 🎀 JUNE Calendar month Teddy B...          coffee   
854   @UnicornSamuel Please open up your PDF ticket ...  Bank/Financial   
2983  RT @yogurljazcxx: hot or cold, coffee is coffe...          coffee   
1816  Citi announced first quarter 2020 results toda...  Bank/Financial   
1822  “In our Institutional Clients Group, we had st...  Bank/Financial   
2365  RT @sagastumecris: when I go over someone’s ho...             dog   
6

In [32]:
accuracy = 100 * np.sum(similar_test_df["original_theme"] == similar_test_df["similar_theme"])/similar_test_df.shape[0]
print("Accuracy on test data in predicting theme: {}%".format(np.round(accuracy,2)))

Accuracy on test data in predicting theme: 87.17%
